services:
  - type: web
    name: drawing-board-websocket
    rootDir: server
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
